# Generated by Django 5.1 on 2024-09-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='main.usuario'),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compradores', to='main.usuario'),
        ),
        migrations.CreateModel(
            name='FavoritoArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_favorito', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comprador')),
            ],
            options={
                'unique_together': {('comprador', 'artista')},
            },
        ),
        migrations.CreateModel(
            name='FavoritoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_favorito', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comprador')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.obra')),
            ],
            options={
                'unique_together': {('comprador', 'obra')},
            },
        ),
    ]
