# Generated by Django 5.1 on 2024-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
