# Generated by Django 5.0.7 on 2024-09-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compradores', to=settings.AUTH_USER_MODEL),
        ),
    ]
